// Plugin setup requirements metadata
// Types:
// - 'token': Simple text/password input
// - 'oauth': OAuth flow (opens browser, localhost callback)
// - 'cli': External setup flow (no CLI in Desktop UI)
// - 'qrcode': Display a QR code generated by the engine
// - 'multi': Multiple fields
// - 'file': File upload
export const PLUGIN_SETUP_REQUIREMENTS = {
    // OAuth-based - built-in OAuth flow with localhost callback
    'google-antigravity-auth': {
        type: 'oauth',
        provider: 'Google Antigravity',
        instructions: 'Authenticate with Google for Antigravity/Cloud Code Assist access. Opens browser for sign-in.',
        configPath: 'env.vars.GOOGLE_ANTIGRAVITY_REFRESH'
    },
    'google-gemini-cli-auth': {
        type: 'oauth',
        provider: 'Google Gemini',
        instructions: 'Authenticate with Google for Gemini API access. Opens browser for sign-in.'
    },
    'copilot-proxy': {
        type: 'oauth',
        provider: 'Copilot Proxy',
        instructions: 'Configure a local Copilot Proxy (base URL + model list). This runs a guided setup flow.',
        docsUrl: 'https://docs.dram.it/providers/models'
    },
    'qwen-portal-auth': {
        type: 'oauth',
        provider: 'Qwen',
        instructions: 'Authenticate with Qwen via device login to enable Qwen Portal models.',
        docsUrl: 'https://docs.dram.it/providers/qwen'
    },
    'minimax-portal-auth': {
        type: 'oauth',
        provider: 'MiniMax',
        instructions: 'Enter your MiniMax API key to enable MiniMax models.',
        docsUrl: 'https://docs.dram.it/providers/minimax'
    },

    // Simple token input
    'telegram': {
        type: 'token',
        label: 'Bot Token',
        placeholder: '123456789:ABCdefGHI...',
        instructions: '1) Open Telegram and chat with @BotFather\n2) Run /newbot (or /mybots)\n3) Copy the token',
        configPath: 'channels.telegram.botToken'
    },
    'discord': {
        type: 'token',
        label: 'Bot Token',
        placeholder: 'MTIzNDU2Nzg5MDEyMzQ1Njc4OQ...',
        instructions: '1) Discord Developer Portal → Applications → New Application\n2) Bot → Add Bot → Reset Token → copy\n3) OAuth2 → invite to your server',
        configPath: 'channels.discord.token'
    },

    // External setup (no CLI required in-app)
    'whatsapp': {
        type: 'qrcode',
        instructions: 'Scan the QR code with WhatsApp on your phone (Settings > Linked Devices).',
    },
    'signal': {
        type: 'multi', fields: [
            { key: 'account', label: 'Bot Number (E.164)', placeholder: '+15551234567' },
            { key: 'cliPath', label: 'signal-cli Path (optional)', placeholder: 'signal-cli', optional: true },
            { key: 'httpUrl', label: 'External Daemon URL (optional)', placeholder: 'http://127.0.0.1:8080', optional: true }
        ], instructions: 'Signal requires a linked signal-cli account or an external daemon. Enter the bot number and connection details.',
        docsUrl: 'https://docs.dram.it/signal'
    },
    'slack': {
        type: 'multi', fields: [
            { key: 'appToken', label: 'App Token (xapp-...)', placeholder: 'xapp-...' },
            { key: 'botToken', label: 'Bot Token (xoxb-...)', placeholder: 'xoxb-...' },
            { key: 'userToken', label: 'User Token (optional)', placeholder: 'xoxp-...', optional: true }
        ], instructions: 'Socket mode uses app + bot tokens. User token is optional and read-only by default.',
        docsUrl: 'https://docs.dram.it/slack'
    },
    'msteams': {
        type: 'multi', fields: [
            { key: 'appId', label: 'App ID', placeholder: '00000000-0000-0000-0000-000000000000' },
            { key: 'appPassword', label: 'App Password', placeholder: 'Client secret', isSecret: true },
            { key: 'tenantId', label: 'Tenant ID', placeholder: '00000000-0000-0000-0000-000000000000' },
            { key: 'webhook.path', label: 'Webhook Path (optional)', placeholder: '/api/messages', optional: true },
            { key: 'webhook.port', label: 'Webhook Port (optional)', placeholder: '3978', optional: true, type: 'number' }
        ], instructions: 'Enter your Azure Bot credentials. Webhook path/port are optional if you use defaults.',
        docsUrl: 'https://docs.dram.it/msteams'
    },

    // Multi-field configs
    'line': {
        type: 'multi', fields: [
            { key: 'channelId', label: 'Channel ID', placeholder: 'LINE channel ID' },
            { key: 'channelSecret', label: 'Channel Secret', placeholder: 'Channel secret', isSecret: true },
            { key: 'accessToken', label: 'Access Token', placeholder: 'Channel access token', isSecret: true }
        ], instructions: 'Get credentials from LINE Developers Console.'
    },
    'matrix': {
        type: 'multi', fields: [
            { key: 'homeserver', label: 'Homeserver URL', placeholder: 'https://matrix.org' },
            { key: 'accessToken', label: 'Access Token (optional)', placeholder: 'Matrix access token', isSecret: true, optional: true },
            { key: 'userId', label: 'User ID (optional)', placeholder: '@bot:example.org', optional: true },
            { key: 'password', label: 'Password (optional)', placeholder: 'Matrix account password', isSecret: true, optional: true },
            { key: 'deviceName', label: 'Device Name (optional)', placeholder: 'DRAM Desktop', optional: true },
            { key: 'encryption', label: 'Encryption (optional)', placeholder: 'true/false', optional: true, type: 'boolean' }
        ], instructions: 'Provide homeserver + access token, or userId + password to log in. Enable encryption after verifying the device.'
    },
    'bluebubbles': {
        type: 'multi', fields: [
            { key: 'serverUrl', label: 'Server URL', placeholder: 'http://localhost:1234' },
            { key: 'password', label: 'Server Password', placeholder: 'BlueBubbles password', isSecret: true }
        ], instructions: 'Get the server URL and password from BlueBubbles app.'
    },
    'mattermost': {
        type: 'multi', fields: [
            { key: 'botToken', label: 'Bot Token', placeholder: 'mm-token', isSecret: true },
            { key: 'baseUrl', label: 'Base URL', placeholder: 'https://chat.example.com' }
        ], instructions: 'Create a Mattermost bot account and enter the bot token + base URL.',
        docsUrl: 'https://docs.dram.it/mattermost'
    },
    'nextcloud-talk': {
        type: 'multi', fields: [
            { key: 'baseUrl', label: 'Base URL', placeholder: 'https://cloud.example.com' },
            { key: 'botSecret', label: 'Bot Secret', placeholder: 'shared-secret', isSecret: true }
        ], instructions: 'Install a Nextcloud Talk bot and enter the base URL + shared secret.',
        docsUrl: 'https://docs.dram.it/nextcloud-talk'
    },
    'nostr': {
        type: 'multi', fields: [
            { key: 'privateKey', label: 'Private Key', placeholder: 'nsec1... or hex', isSecret: true },
            { key: 'relays', label: 'Relays (optional)', placeholder: 'wss://relay.damus.io, wss://nos.lol', optional: true, type: 'list' }
        ], instructions: 'Enter your Nostr private key to enable DM support. Optionally set relays.',
        docsUrl: 'https://docs.dram.it/nostr'
    },
    'tlon': {
        type: 'multi', fields: [
            { key: 'ship', label: 'Ship', placeholder: '~sampel-palnet' },
            { key: 'url', label: 'Ship URL', placeholder: 'https://your-ship-host' },
            { key: 'code', label: 'Login Code', placeholder: 'lidlut-tabwed-...', isSecret: true }
        ], instructions: 'Enter your Urbit ship details to connect Tlon.',
        docsUrl: 'https://docs.dram.it/tlon'
    },
    'twitch': {
        type: 'multi', fields: [
            { key: 'username', label: 'Bot Username', placeholder: 'moltbot' },
            { key: 'accessToken', label: 'Access Token', placeholder: 'oauth:...', isSecret: true },
            { key: 'clientId', label: 'Client ID', placeholder: 'xyz123...' },
            { key: 'channel', label: 'Channel', placeholder: 'yourchannel' }
        ], instructions: 'Create a Twitch bot token and enter the username, token, client ID, and channel.',
        docsUrl: 'https://docs.dram.it/twitch'
    },
    'zalo': {
        type: 'token',
        label: 'Bot Token',
        placeholder: '12345689:abc-xyz',
        instructions: 'Create a Zalo bot token and paste it here.',
        configPath: 'channels.zalo.botToken',
        docsUrl: 'https://docs.dram.it/zalo'
    },
    'zalouser': {
        type: 'qrcode',
        instructions: 'Scan the QR code with the Zalo mobile app to link your personal account.',
        docsUrl: 'https://docs.dram.it/zalouser',
    },
    'imessage': {
        type: 'multi', fields: [
            { key: 'cliPath', label: 'imsg CLI Path', placeholder: 'imsg' },
            { key: 'dbPath', label: 'Messages DB Path', placeholder: '/Users/you/Library/Messages/chat.db' },
            { key: 'remoteHost', label: 'Remote Host (optional)', placeholder: 'user@mac-host', optional: true },
            { key: 'service', label: 'Service (optional)', placeholder: 'imessage | sms | auto', optional: true },
            { key: 'region', label: 'SMS Region (optional)', placeholder: 'US', optional: true }
        ], instructions: 'Provide the imsg CLI path and Messages DB path. If using a remote Mac, point cliPath to an SSH wrapper and set remoteHost.',
        docsUrl: 'https://docs.dram.it/imessage'
    },

    // File upload
    'googlechat': {
        type: 'file',
        label: 'Service Account JSON',
        instructions: 'Upload the service account credentials JSON from Google Cloud Console.',
        configPath: 'channels.googlechat.serviceAccount',
        fields: [
            { key: 'audienceType', label: 'Audience Type', placeholder: 'app-url' },
            { key: 'audience', label: 'Audience', placeholder: 'https://gateway.example.com/googlechat' },
            { key: 'webhookUrl', label: 'Webhook URL (optional)', placeholder: 'https://gateway.example.com/googlechat', optional: true },
            { key: 'webhookPath', label: 'Webhook Path (optional)', placeholder: '/googlechat', optional: true },
            { key: 'botUser', label: 'Bot User (optional)', placeholder: 'users/1234567890', optional: true }
        ]
    },

    // Plugin configs
    'voice-call': {
        type: 'multi', fields: [
            { key: 'provider', label: 'Provider', placeholder: 'twilio | telnyx | plivo | mock', configPath: 'plugins.entries.voice-call.config.provider' },
            { key: 'fromNumber', label: 'From Number', placeholder: '+15550001234', configPath: 'plugins.entries.voice-call.config.fromNumber' },
            { key: 'toNumber', label: 'Default To (optional)', placeholder: '+15550005678', optional: true, configPath: 'plugins.entries.voice-call.config.toNumber' },
            { key: 'twilio.accountSid', label: 'Twilio Account SID', placeholder: 'ACxxxxxxxx', optional: true, configPath: 'plugins.entries.voice-call.config.twilio.accountSid' },
            { key: 'twilio.authToken', label: 'Twilio Auth Token', placeholder: '...', isSecret: true, optional: true, configPath: 'plugins.entries.voice-call.config.twilio.authToken' },
            { key: 'telnyx.apiKey', label: 'Telnyx API Key', placeholder: 'KEY...', isSecret: true, optional: true, configPath: 'plugins.entries.voice-call.config.telnyx.apiKey' },
            { key: 'telnyx.connectionId', label: 'Telnyx Connection ID', placeholder: '1234567890', optional: true, configPath: 'plugins.entries.voice-call.config.telnyx.connectionId' },
            { key: 'telnyx.publicKey', label: 'Telnyx Public Key', placeholder: '-----BEGIN PUBLIC KEY-----', optional: true, configPath: 'plugins.entries.voice-call.config.telnyx.publicKey' },
            { key: 'plivo.authId', label: 'Plivo Auth ID', placeholder: 'MAxxxxxxxx', optional: true, configPath: 'plugins.entries.voice-call.config.plivo.authId' },
            { key: 'plivo.authToken', label: 'Plivo Auth Token', placeholder: '...', isSecret: true, optional: true, configPath: 'plugins.entries.voice-call.config.plivo.authToken' },
            { key: 'serve.port', label: 'Webhook Port (optional)', placeholder: '3334', optional: true, type: 'number', configPath: 'plugins.entries.voice-call.config.serve.port' },
            { key: 'serve.path', label: 'Webhook Path (optional)', placeholder: '/voice/webhook', optional: true, configPath: 'plugins.entries.voice-call.config.serve.path' },
            { key: 'publicUrl', label: 'Public URL (optional)', placeholder: 'https://example.ngrok.app/voice/webhook', optional: true, configPath: 'plugins.entries.voice-call.config.publicUrl' }
        ],
        instructions: 'Configure your voice provider, numbers, and webhook. Provider credentials are required for live calls.',
        docsUrl: 'https://docs.dram.it/plugins/voice-call'
    }
};

export const PLUGIN_INSTALL_ACTIONS = {
    'msteams': {
        command: 'dram plugins install @moltbot/msteams',
        docsUrl: 'https://docs.dram.it/msteams'
    },
    'line': {
        command: 'dram plugins install @moltbot/line',
        docsUrl: 'https://docs.dram.it/line'
    },
    'mattermost': {
        command: 'dram plugins install @moltbot/mattermost',
        docsUrl: 'https://docs.dram.it/mattermost'
    },
    'matrix': {
        command: 'dram plugins install @moltbot/matrix',
        docsUrl: 'https://docs.dram.it/matrix'
    },
    'nostr': {
        command: 'dram plugins install @moltbot/nostr',
        docsUrl: 'https://docs.dram.it/nostr'
    },
    'twitch': {
        command: 'dram plugins install @moltbot/twitch',
        docsUrl: 'https://docs.dram.it/twitch'
    },
    'nextcloud-talk': {
        command: 'dram plugins install @moltbot/nextcloud-talk',
        docsUrl: 'https://docs.dram.it/nextcloud-talk'
    },
    'tlon': {
        command: 'dram plugins install @moltbot/tlon',
        docsUrl: 'https://docs.dram.it/tlon'
    },
    'zalo': {
        command: 'dram plugins install @moltbot/zalo',
        docsUrl: 'https://docs.dram.it/zalo'
    },
    'zalouser': {
        command: 'dram plugins install @moltbot/zalouser',
        docsUrl: 'https://docs.dram.it/zalouser'
    },
    'voice-call': {
        command: 'dram plugins install @moltbot/voice-call',
        docsUrl: 'https://docs.dram.it/plugins/voice-call'
    }
};




